name: Ubuntu Setup

# Nhận code cài đặt và mã pin remote desktop
on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Vui lòng nhập mã cài đặt cho Linux ở link sau: https://remotedesktop.google.com/headless'
        required: true
      pincode:
        description: 'Nhập mã pin remote desktop (6 số)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Đang tạo user
        run: |
          sudo useradd -m huyannet
          sudo adduser huyannet sudo
          echo 'huyannet:123456' | sudo chpasswd
          sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
      - name: Đang cài giao diện đồ họa
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install --assume-yes wget xfce4 desktop-base xbase-clients xfce4-terminal 
          sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
          sudo apt remove --assume-yes gnome-terminal
          sudo apt remove --assume-yes xscreensaver
          sudo systemctl disable lightdm.service
          sudo apt install --assume-yes --fix-broken

      - name: Đang cài đặt Chrome Remote Desktop
        run: |
          sudo wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg --install chrome-remote-desktop_current_amd64.deb
          sudo apt install --assume-yes --fix-broken
          
      - name: Đang thiết lập các tùy chỉnh
        run: |
          sudo bash
          ${{ github.event.inputs.authcode }} --pin=${{ github.event.inputs.pincode }}
          wget https://dl.google.com/linux/linux_signing_key.pub; wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; dpkg --install chrome-remote-desktop_current_amd64.deb; apt-key add /tmp/linux_signing_key.pub; dpkg --install google-chrome-stable_current_amd64.deb; apt install --assume-yes --fix-broken; apt-get clean; rm -rf /var/cache/* /var/log/apt/* /var/lib/apt/lists/*;useradd -m -G chrome-remote-desktop,pulse-access chrome;usermod -s /bin/bash chrome; ln -s /crdonly /usr/local/sbin/crdonly; ln -s /update /usr/local/sbin/update;mkdir -p /home/chrome/.config/chrome-remote-desktop;mkdir -p /home/chrome/.fluxbox'
          sudo adduser huyannet chrome-remote-desktop
          sudo service chrome-remote-desktop restart


